### ISSUE TITLE
Subtitles on video if captions enabled via keyboard shortcut

### ISSUE THREAD

**Issue by azizLIGHT** [t1ml3arn-userscript-js/Youtube-subtitles-under-video-frame#1]
The script works fine if you click the captions button with the mouse
However, if you press the keyboard shortcut c to enable captions, then the captions appear on top of the video instead of under the video frame
You can alternate between the two positions if you try the mouse button and then try the keyboard button c, without needing to refresh the page or load the video from scratch

**Comment by T1mL3arn** [comment]
Thanks for bringing this up. It is fixed with 7bca3610651e47b823b729ab543e8009bd80c701.
